services:
  frontend:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./OJ/dist:/usr/share/nginx/html
      - ./OJ/nginx.conf:/etc/nginx/nginx.conf:ro  
    depends_on:
      - backend

  backend:
    build: ./oj-auth-backend
    ports:
      - "5050:5050"
    env_file:
      - ./oj-auth-backend/.env
    environment:
     - MONGO_URI=mongodb://host.docker.internal:27017/ojdb
     - COMPILER_URL=http://compiler-service:6000
    depends_on:
      - mongo
      - compiler-service

  compiler-service:
    build: ./compiler-service
    ports:
      - "6000:6000"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
