version: "3.8"

services:
  frontend:
    image: nginx:latest
    container_name: oj-frontend
    ports:
      - "3000:80"
    volumes:
      - ./OJ/dist:/usr/share/nginx/html
      - ./OJ/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - oj-net

  backend:
    build: ./oj-auth-backend
    container_name: oj-backend
    ports:
      - "5050:5050"
    env_file:
      - ./oj-auth-backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/ojdb
      - COMPILER_URL=http://compiler-service:6000
    depends_on:
      - mongo
      - compiler-service
    networks:
      - oj-net

  compiler-service:
    build: ./compiler-service
    container_name: compiler-service
    ports:
      - "6000:6000"
    networks:
      - oj-net

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - oj-net

volumes:
  mongo_data:

networks:
  oj-net:
    external: true
